name: Douglas
favicon: null
layout_spectrum: 0.1603648983873427
typography_spectrum: 0.285536470124498
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.3966498386580497
  lightness: 0.8268422265537083
  saturation: 0.7386852682102472
  rhythmicContrast: 0.09323121281340718
purpose: []
